# -*- compile-command: "./compile.sh" -*-
#+TITLE: A novel, multi-model, multi-task, method for computerized testing of emotional intelligence
#+AUTHOR: William Rudenmalm
#+EMAIL: me@whn.se
#+BIBLIOGRAPHY: refs plain
#+OPTIONS: num:4 toc:nil
#+LaTeX_HEADER: \input{preamble.tex}

\input{toc.tex}

* Introduction
  Emotions play a fundamental role in modulating the behavior and experiences
  of organisms, and while the exact definition is debated, its
  importance is not \parencite{Scherer2005}. The impact that emotions
  have on everyday life is enormous yet hard to pinpoint.
  
  \citet{Fontaine2007} defines emotions as a set of interrelated
  components, covering a wide range of behavior. These are appraisals
  of events, psychophysiological changes, motor expressions, action
  tendencies, subjective experience, and emotion regulation
  \parencite{Fontaine2007}. Emotions may have both internal
  and external antecedents \parencite{Scherer2005}.
  
  One important purpose of emotions is regulating social interactions
  by facilitating group cohesion and collaboration. Understanding the
  emotions of others is an essential aspect of many social
  situations. \parencite{Niedenthal2012}.
  
  The ability to process the emotional information contained both in
  oneself and others is referred to in the literature as emotional
  intelligence. Emotional intelligence has over the last
  two-and-a-half decades gained the attention of researchers. This
  ability to can be conceptualized as differences in the extent to
  which organisms interpret, process and act upon the emotions and
  affects of themselves and others. An essential component in
  emotional intelligence seems to be the ability to identify the
  emotions of oneself and others. \parencite{Mikolajczak2014} 
  
  The concept of emotional intelligence is not uncontroversial, with
  different authors suggesting widely different models of emotional
  intelligence \citep{McCleskey2014,Mayer2008,Petrides2010}. Other
  authors (TK, Who? Locke surely) have questioned the validity of
  emotional intelligence. Indeed, emotional intelligence has been
  found to correlate with personality factors
  \citep[e.g.][]{Warwick2004, Petrides2001} and cognitive abilities
  \citep[e.g.][]{Freudenthaler2007}. These correlations call into
  question the divergent validity, to that point of some authors (TK
  Locke and someone else) doubting the concepts usefulness.
  
  Several approaches have been used to measure emotional intelligence,
  both ability tests \citep{Mayer2003}, self-reported ability
  \citep{Bar-On1997}, and trait measures (TK, ref).
  \citet{Mikolajczak2014} approached the measuring of emotional
  intelligence and developed a 50-item inventory for emotional
  intelligence. More specialized \citet{Baron-Cohen2001} approached
  the problem from a different angle asking participants to identify
  an emotion based just on a picture showing a pair of eyes. Another
  strand of research focuses on measuring emotional facial recognition
  \parencite{Schlegel2012}. The results of \citet{Schlegel2012} seem
  to indicate that the recognition of b emotional faces is a single
  ability as opposed to multiple separate abilities, affirming to some
  degree the convergent validity to the construct of emotional
  intelligence.
  
  One approach that might be taken for emotional intelligence testing
  is using emotional facial expressions in a manner similar to
  \citet{Schlegel2012}. Indeed facial expressions, \citet{Ekman1969a}
  found, are to a large extent culturally invariant. The set of
  culturally invariant basic emotions \citet{Ekman1992} later defined
  as anger, fear, sadness, enjoyment, disgust and surprise.

  Cultural invariance is an important property for tests of emotional
  intelligence, suggesting that micro-expression recognition may be an
  appropriate measure of emotional competency. Indeed,
  \citet{Ekman2003} introduced the brief affect recognition task
  (BART) as a means by emotion recognition can be measured. One trial in
  the BART paradigm consists of a display of an emotional facial
  expression with forward- and backward masks of a neutral emotional
  face to avoid after-images \citep{Ekman2003}.

** Research problem
   Testing and training applications being a central part of
   micro-expression research \citep{Ekman1992}. However, despite
   multiple several studies being made \citep[e.g.][]{Schlegel2012},
   there exists no standard for testing emotion recognition using
   micro-expressions.

   The lack of a standard for testing emotion recognition may suggest
   a lack of understanding of what factors are important for
   developing tools for testing emotional intelligence. The present
   study sets out improve the understanding of how such testing
   software could be designed and aims to improve the accuracy and
   availability of such tests.

   The creation of such principles could be relevant for a number of
   areas. Firstly, education of psychologists, psychotherapists, and
   other mental health professionals might benefit from improved
   training tools. Second, applications in recruiting situations may
   help organizations make better recruitment decisions. Finally,
   psychological tests using the micro-expression paradigm may be
   improved using the principles.
     
** Research question
   What are the key principles for developing EQ-tests based on micro-expressions?
  
* Extended background


** The Theoretical Models of Emotional Intelligence
   The definition of emotional intelligence has since its inception
   been the subject of fierce debate \citep{McCleskey2014}. One of the
   key sources of controversy is whether emotional intelligence is to
   be considered an ability \citep{Salovey1990}, a competency that can
   be learned \citep{Baron2006} or personality trait
   \citep{Petrides2007}. This disagreement on the definition of the
   concept might at first seem superifical but lies at the core in the
   issue of measuring and understanding emotional intelligence. (TK
   Something about Goleman model)

   The notion of emotional intelligence as a competency is primarily
   advocated by \citep{Baron2006}. The Bar-On model is defined more
   precisely as a "cross-section of interrelated emotional and social
   competencies, skills and facilities that determine how effectively
   we understand and express ourselves, understand others and relate
   with them, and cope with daily demands" \citep{Baron2006}. The
   model is consistent with other frameworks in including both inter-
   and intra-personal skills. Like most other models of emotional
   intelligence, the Bar-On model considers widely different tasks,
   ranging from recognition to regulating emotions. (TK; REF)

   Writing only years after Bar-On (TK, Doctoral dissertation)
   \cite{Salovey1990} introduced their notion of emotional
   intelligence, with the widely cited (TK, e.g) passage defining
   emotional intelligence as ``the subset of social intelligence that
   involves the ability to monitor one's own and others' feelings and
   emotions to discriminate among them and to use the information to
   guide one's thinking and actions''.  \citet{Salovey1990} also
   divided emotional intelligence into four sub-categories of
   emotional intelligence these are: appraisal, expression, regulation
   and, utilization. \citet{Salovey1990} argue that people exhibiting
   these abilities may show more adaptive behaviors
   \citep{Brackett2006}. Conversely, people exhibiting deficits in
   emotional intelligence may show maladaptive behaviors
   \citep{Brackett2006}.

   Beginning with \citet{Petrides2001}, one strand of research has
   separated emotional intelligence into trait and ability components
   \citep[e.g.][]{Petrides2007, Petrides2010}. Indeed, a growing body
   of evidence seems to indicate that personality factors explain some
   parts of emotional intelligence
   \citep[e.g.][]{Warwick2004,Petrides2001}. Specifically,
   \citet{Warwick2004} found correlations between personality factors
   and trait emotional intelligence. Building on these results
   \citet{Petrides2007}, argues that while trait emotional
   intelligence is a personality trait and uncorrelated with ability
   measures of emotional intelligence, it is distinct from traditional
   personality factors. The incompatibility argument is expanded
   further by \citet{Petrides2010}, arguing that trait and ability
   measures of emotional intelligence cannot be grouped in any
   meaningful sense. Moreover, \citet{Petrides2010} criticizes the
   Bar-On \citep{Baron2006} model as well as the \citet{Salovey1990}
   model, arguing that ability measures of emotional intelligence
   imply the existence of some universal notion of adaptive social
   behavior.

   To resolve some of the controversies surrounding the definition of
   the term \citet{Cherniss2010} suggests separating the concepts of
   emotional intelligence and social competence. Thereby defining
   emotional intelligence simply as the recognizing, reasoning and
   regulating emotions, holding that other factors are simply
   emotional and social competencies. In effect \citet{Cherniss2010},
   designates the \citet{Salovey1990} model as emotional intelligence,
   while referring to the Bar-On model \citep{Baron2006} as emotional
   and social competence. This attempt to reconcile different theories
   of emotional intelligence was criticized by \cite{Petrides2010} for
   severing the link between the constructs and their present
   operational definitions.

   The separation of trait and state concepts of emotional
   intelligence is supported by most authors
   \citep[e.g.][]{Petrides2010,McCleskey2014,DiFabio2014} (TK,
   Askhanasy). What this separation entails, however, is a matter of
   debate. Proponents of the trait model of emotional intelligence
   such as \citet{Petrides2010} argue that ability measures of
   emotional intelligence are lacking. While proponents of the ability
   model argue that trait models just measure various aspects of
   personality. Another approach was taken by
   \citet{Freudenthaler2007}, interpreting trait and ability as
   typical and maximum performance respectively, finding typical
   performance as dependent on personality and maximum performance as
   dependent on cognitive ability.

   Some limited agreement can perhaps be captured as follows:
   emotional intelligence is a continuous factor determining the depth
   and accuracy of processing at the crossroads of emotion and
   cognition. Even if earlier intergrative approaches have been
   critized \citep[e.g ][]{Cherniss2010}, multifaceted approaches may
   still be valuable, however this would require combining the
   theoretical multiple theoretical frameworks.
    
** Uses for emotional intelligence
   
   Desipte the difficulty of accurately defining the term, proponents
   of emotional intelligence argue its usefulness.  In a review by
   \citet{Mayer2008} identified seven central results of emotional
   intelligence research, these were:
#+BEGIN_QUOTE
   1. Better social relations for children.
   2. Better social relations for adults. Among
   3. High-EI individuals are perceived more positively by others.
   4. Better family and intimate relationships.
   5. Better academic achievement. [not accounting for IQ]
   6. Better social relations during work performance and in negotiations.
   7. Better psychological well-being.
#+END_QUOTE

   Within the areas mentioned by \citet{Mayer2008}, it seems that
   measures emotional intelligence, at least degree predicts
   outcomes. The results within these areas suggest that instruments
   measuring emotional intelligence may be useful

   Another area discussed is the relationship of emotional
   intelligence and leadership. Indeed, it is commonly held that
   emotional intelligence plays a role in leadership
   \citep{Brackett2006,McCleskey2014}. \citet{McCleskey2014} argues
   that for at least some aspects of leadership, it seems likely that
   emotional intelligence offers at least some predictive value for
   leadership roles \citep{McCleskey2014}.
   
   Moreover, emotional intelligence scales have been used for
   corporate recruiting for roles requiring social
   interaction. Indeed, these results seem to suggest that emotional
   intelligence may be useful in guiding hiring decisions (TK, REF)

   Finally, the concept of emotional intelligence is useful in the
   diagnosis and testing for autism spectrum disorders
   \parencite{Baron-Cohen2001}. In this particular case, a specific
   test of emotion recognition, reading the mind in the eyes, was
   developed \citep{Baron-Cohen2001}.

** Measuring emotional intelligence of Ability

   Like with its definition, how emotional intelligence is measured is
   also debated. There exists no universally accepted standard for
   measuring emotional intelligence. The different scales of emotional
   intelligence usually fall into one of only one of the theoretical
   models of emotional intelligence.
   
    An early measure of emotional intelligence is the
    Mayer-Salovey-Caruso Emotional Intelligence (MSCEIT), which is
    based on the theoretical framework introduced by
    \citep{Salovey1990}. In version 2.0 it consisted of 141 items
    across four facets of emotional intelligence
    \citep{Mayer2003}. MSCEIT attempts measure performance based on a
    set of eight tasks with two for each facet \citep{Mayer2003}. The
    MSCEIT tasks cover a number of emotional abilities including
    recognition of emotional pictures and faces, understanding and
    managing them \citep{Mayer2003}. One differentiating aspect of
    MSCEIT is its focus on emotional problem-solving. In an evaluation
    of MSCEIT 2.0 \citet{Mayer2003} found both sufficiently reliable
    as well as consistent with its theoretical foundations. The
    validity however been disputed, \citet{Rossen2008} found results
    running contrary to the factor structure used found by
    \citet{Mayer2003}. The results found by \citet{Rossen2008} seem to
    suggest that the sub-scales do not match the intended theoretical
    concepts. For measuring trait emotional intelligence,
    \cite{Salovey1995} introduced Trait meta-mood scale (TTMS) which
    aims to measure the tendency to attend to one's moods and
    emotions. The TTMS scale has been found not to correlate with
    MSCEIT, indicating that it is a separate construct from ability
    measured by MSCEIT \citep{Warwick2004}.

    Another interesting inventory for measuring emotional intelligence
    is the Profile of Emotional Competence (PEC), consisting of 50
    items divided into ten sub-scales \citep{Brasseur2013}. The PEC
    shows a good internal consistency, making it appropriate for both
    clinical and research use \citep{Brasseur2013}.

    Recently, \citet{Mikolajczak2014} were able to reduce the earlier
    PEC scale to only 20 items while maintaining the predictive
    properties of the original 50-item scale. This result suggests that
    emotional intelligence can be measured using only a small number
    of questions.

    Another method of measuring is Emotional Quotient-Inventory
    (EQ-I), a standard questionnaire consisting of 131-items divided
    five sub-scales with three facets each for a total of 15 ratings
    \citep{Bar-On1997}. The EQ-I is built on the theoretical framework
    based on emotional intelligence as a competency
    \citep{Baron2006}. EQ-I is often used both on an individual and a
    peer-level, where peers are asked to rate the individual's
    emotional intelligence. The approach of using peer ratings has
    recently found support in \citet{Elfenbein2015}, showing that such
    peer ratings are both accurate and reliable.

    The EQ-I is not without its problems. One large problem is that of
    fakeability, in one study conducted by \citet{GrubbIII2007}, found
    that participants when asked to "fake" emotional intelligence were
    able to do so. Such fakeability is quite troublesome because it
    would imply that it does not measure a competency, which would
    have been difficult to fake.

** Measures related to emotional intelligence

   Outside the development of psychometric scales of emotional
   intelligence, some research has also gone into examining other
   aspects and ways of measuring emotional intelligence and related
   areas. Over time, a wide variety of tasks have been developed for
   assessing emotion intelligence. These scales are often developed
   outside the area of emotional intelligence, and are to some degree
   unaffected by the controversy surrounding other measures of
   emotional intelligence.

   One measure that might be considered emotional intelligence is the
   reading the mind in the eyes (RTMITE) task \citet{Baron-Cohen2001},
   which has been successful in distinguishing people with Asperger
   Syndrome and high-functioning autism controls. The instrument has
   shown good test-retest reliability \citep{Hallerback2009} and has
   been applied in a number of cultures
   \citep{Yildirim2011,Hallerback2009}.

   Another measure related to emotions is the Toronto Alexithymia
   Scale (TAS), a 20-item scale for detecting alexithymia. The TAS
   consists of two subscales difficulty identifying feelings and
   difficulty describing feelings \cite{Bagby1994}. The measure has
   shown good validity \citep{Bagby1994}. Further evidence for its
   validity were found by \citet{Bressi1996} showing that good
   validity could also be obtained for Italian populations, suggesting
   at least some degree of cultural invariance. Finally, in a
   functional magnetic resonance imaging (fMRI) study,
   \citet{Berthoz2002} found differences in the activation of the
   anterior cingulate cortex and the mediofrontal cortex between high
   people with high TAS-scores and controls. These results suggest an
   underlying neural basis for the TAS and alexithymia, in general.

** Recognition of emotional faces
   A separate but related field to traditional emotional intelligence
   testing is the recognition of emotional facial expressions. This
   strand of research builds on the work of \cite{Ekman1969a}. The
   model of emotions advanced by Ekman identifies a set of basic
   emotions that are culturally independent \citep{Ekman1987}, occur
   automatically \citep{Ekman1992,Ekman1997} and are automatically
   processed \cite{Ekman1992}.

   Another feature of Ekman's is emotional leakage that occurs when
   consciously trying to suppress the expression of some emotion
   \citep{Ekman1969,Ekman2003}. This emotional leakage, what Ekman
   refers to as micro expressions can be identified by others
   \citep{Ekman1974}. Both individual and group differences in the
   ability to detect deceit have been found. For example,
   \cite{Ekman1991} found that some professional groups (e.g. the
   U.S. Secret Service) are better at detecting deceit, using both
   verbal and non-verbal cues \cite{Ekman1991}. Another result is that
   of \citet{Frank1997}, which seems to suggest that the ability to
   detect deceit is generalized to a large number of situations.

   #+BEGIN_LATEX
   \begin{figure}[htpb]
   \centering
   \label{fig:mett}
   \includegraphics[width=0.5\textwidth]{diamett}
   \caption[Visual representation of the METT paradigm]{One complete trial in the METT paradigm, consisting of a forward mask, a stimulus and a backward mask. The pictures used in this example are taken from the KDEF data-set.}
   \end{figure}
   #+END_LATEX

   Based on this theoretical framework \cite{Ekman1974a} introduced
   the Brief Affection Recognition Test (BART), consisting of very
   brief displays of emotional facial expressions (under
   200ms). Paradigms based on the BART been used widely
   \cite[e.g.][]{Matsumoto2000}. By only showing the facial expression
   for a short time, accuracy is reduced. Ensuring that the
   chance-adjusted is as close to 50% is important to avoid floor and
   ceiling effects, which could distort the data. Another important
   feature of BART is its use masking images of neutral faces both
   before and after a trial \citep{Ekman1974a}. This masking serves
   both to provide a fixation point before the trial, and ensure that
   the participants do not have the benefit of after-images. This
   paradigm is illustrated in \ref{fig:mett}

   Another method of ensuring low enough accuracy is the subtle
   expression training tool (SETT). Unlike the BART, expressions are
   restricted to one part of the face. This restriction is meant to
   simulate a situation where the person is consciously suppressing a
   facial expression. \citep{Ekman2003}

** Stimulus sets of emotional expression

   To use the paradigms discussed it is necessary to use a set of
   photographs. Because recognition of facial expressions is a common
   task there exists a plethora of facial expression stimulus
   sets. These stimulus sets have been created for a number of
   different purposes and are suitable for many different kinds of
   research. For the present study, we will review a number of
   different stimulus sets and the research validating them.

   One early stimulus set is the Japanese and Caucasian Facial
   Expressions of Emotion \citep[JACFEE;][]{matsumoto1988japanese}.
   JACFEE consists of 56 photos of models of Japanese or Caucasian
   decent with eight pictures, one for each basic emotions, and one
   neutral picture \citep{matsumoto1988japanese}. The dataset, while
   showing substantial cross-national differences also showed
   relatively high levels of agreement \citep{Biehl1997}.

   Another common data-set of emotional facial expression is the
   Karolinska Directed Emotional Faces
   \citep[KDEF;][]{DanielLundqvistAndersFlykt1998}. KDEF consists of
   pictures 70 of individuals expressing seven different emotions
   from five angles. KDEF has, since its inception, seen much use in
   facial expression research
   \citep[e.g.][]{Calvo2008a,Willis2006,Todorov2009}. In addition to
   widespread use, KDEF has shown good test-retest validity and a
   high degrees of accuracy in recognition tasks
   \citep{Goeleven2008}.

   \citet{Beaupre2000} approached the issue of finding a good stimulus
   set from the perspective of cultural difference in the ability to
   recognize emotions. The Montreal Set of Facial Displays of Emotion
   \citep[MSFDE][]{Beaupre2000} consists of facial expressions
   instructed to follow the FACS codes. The full stimulus set consists
   of 144 images, with six types of facial expressions and three
   ethnic groups: French Canadians, Chinese, and sub-Saharan Africans.
   The MSFDE was validated in \citet{Beaupre2005} as a large degree of
   cultural invariance.

   Yet another set is NimStim \citep{Tottenham2009}, consisting of 672
   images of 43 professional actors instructed to pose eight different
   emotions, in both open and closed mouthed expressions. In their
   evaluation \citet{Tottenham2009}, found that the reliability of the
   set was good. They also selected a recommended subset of the images
   for which reliability is good, for use in future studies.

   A more recent contribution is the Radboud Faces Database
   \citep[RaFD;][]{Langner2010}. RaFD contains photographs of 49
   models expressing eight emotions with three gaze directions, taken
   from five camera angles for a total 5880 photographs
   \citep{Langner2010}. Upon validation, RaFD showed a very high
   accuracy, higher even than the earlier KDEF dataset
   \citep{Langner2010}. A key difference between RaFD and KDEF is the
   expression coaching given to models by a facial expression coding
   expert, which may explain the higher accuracy rates in RaFD
   \citep{Langner2010}.

   \citet{Calvo2008a} investigated the relationship between the
   display time (25-500ms) and the accuracy of emotion recognition
   for the KDEF stimulus set and found a slight increase in accuracy
   for longer displays. In addition, \citet{Calvo2008a} found
   differences in detection between the emotions. Happy and neutral
   showed higher degrees of accuracy than the other emotions and fear
   showed a lower accuracy.

   The results of \citet{Calvo2008a} suggest that there are
   differences in the accuracy of processing different emotions. Most
   importantly, it seems that accuracy rates for facial expressions of
   happiness and neutral expressions are much higher than those of
   other the expressions \citep{Calvo2008a}. Care must, therefore, be
   taken so as to avoid ceiling effects in general and happiness in
   particular.

   Another strand of research has gone into the split-second trait
   judgments made viewing a face. \cite{Willis2006} found very
   strong correlations between judgments of trustworthiness made
   after \SI{100}{\milli\second} or \SI{500}{\milli\second} versus
   those made without any time constraint. Moreover, no significant
   difference was found between the \SI{100}{\milli\second} and
   \SI{500}{\milli\second} conditions, suggesting that a trait
   judgment is performed very quickly. This notion was further
   expanded by \citet{Todorov2009}, finding that accuracy with
   display times up to \SI{100}{\milli\second}, after which the
   growth rate is dramatically slower.

   One problem with all stimulus sets discussed in that they consist
   of still images of facial expression. It could be argued that the
   dynamics of facial expressions play an important role in the
   recognition of facial expressions. To has lead to the development
   of a number of video-based stimulus-sets for facial expression. The
   Geneva Multimodal Emotion Portrayals
   \citep[GEMEP;~][]{Banziger2012} is one of these. The GEMEP utilizes
   contains audio and video for each expressions providing three
   options for stimulus displays, audio-only, video-only,
   audio-video. The GMEP stimulus-set is extensive, with a total set
   of 1260 expressions, spread out over eighteen emotions, ten actors,
   three angles and a varying number of repetitions and different
   verbal content \citep{Banziger2012}.

   Based on the research discussed in this review, it could be argued
   that measuring the recognition facial expressions may be
   successful in finding individual differences in emotional
   processing. This difference seems particularly pronounced at low
   display times.

* Methodology and Methods for Data Collection
   The goal of the present study is not merely empirical, it aims
   instead to design a set of principles for computerized tests of
   emotional intelligence. This distinction is discussed further by
   \citet[chapter 1]{Johannesson2014}, who hold that practical
   problems ought to be addressed with design research approaches.
    
   \citet[chapter 4]{Johannesson2014} put forward a model of design
   science based on five activities. The first activity, Explicate
   problem, aims to find the practical problems that needs
   solving. The second activity Define requirements, finds what
   requirements should be included in the artefact. The third stage,
   design and develop artefact concerns the creation of the actual
   artefact. The fourth stage, Demonstrate artefact aims to
   demonstrate that the artefact solves the actual problem. Evaluate
   artefact where the extent to which the artefact solves the intended
   problem.

   By using these stages, \citet{Johannesson2014} argue that the
   successful application helps researchers decide on a what to
   develop, develop an artefact and evaluate it.


** Different variants of design science
   Comparing Perjons & Johannesson v.s. earlier descriptions and our
   chosen approach.


** Chosen stages
   Because of limitations in scope only a subset of design science
   activities were performed in the present study. To ensure that a
   viable product was developed, even without considering some of the
   design science stages, a selection of stages had to be made.  The
   following stages were selected because they are the fastest way to
   reach an actual artefact given the limitation in scope:
   - Requirements definition
   - Implementation
   - Evaluation

** Choice of Method
   For each chosen stage in the design science process, different
   methodological considerations were made. These are discussed
   separately below.  For the purposes of the present study a number
   of approaches were considered. \citet{Denscombe2010} covers a
   number of research strategies.

*** Requirements definition
    An extensive number of researh methods can be used for defining
    requirements. Many popular approaches directly involve potential
    stakeholders directly \citet[chapter 6]{Johannesson2014}. One
    oft-used method is surveys allowing for coverage of potential
    requirements \citep[chapter 6]{Johannesson2014}. Using surveys
    runs the risk of being able to find innovative requirement that
    the stakeholders were unable to identify.
    \citet[chapter~6]{Johannesson2014} suggest using other methods
    such as case studies and action research to find requirements that
    the stakeholders were unable to identify. These methods however
    have the drawback of applying the researchers personal views on
    the requirements \citep[chapter 6]{Johannesson2014}.

    The domain of the present study is complex. Test-takers are
    unlikely to understand the intricate nature of the subject area,
    and their interests do not align with the people administering the
    test. Similarly, practitioners in the area often have little
    understanding of the tests they administer. Finally, it is
    difficult to find a significantly large population of researchers
    on the area to establish qualitative saturation. This would in
    the view of \citep[chapter~6]{Johannesson2014} restrict the
    studies to documents.

    It could be argued that using only documents would be sub-optimal
    for many IS studies. In the case of the present study, however the
    situation is very different.

    To successfully capture the requirements for the present study
    two methods were chosen:
   - A literature review for emotional intelligence
   - A quantitative analysis of existing data collected from a
     micro-expression test.

   These methods were chosen to successfully capture variance from
   both the scientific literature as well as empirical data. The
   combination of different kinds of methods allow for better
   capturing the relevant aspects of emotional intelligence and
   reaching sufficient coverage of the domain.
     
   The literature review was chosen to ensure a sufficient degree of
   qualitative coverage of the area of research, this is particularly
   important because of the controversial nature of the concept of
   emotional intelligence. Thus allowing for capturing a reasonably
   agreed upon definition of emotional intelligence.
   
   The quantitative analysis of earlier data constitutes experimental
   method \citet{Denscombe2010}, because the data was collected in a
   experimental settings. The existence of prior data, motivates the
   choice of quantitative analysis of data gathered by experimental
   methods, because this data is already collected using it has very
   low costs. Analysis of such data would allow for empirical answers
   to questions which may be relevant for the study.

   By combining an explorative literature study, giving insights into
   various different areas of emotional intelligence, with an
   empirical analysis of earlier data, the present study can define
   requirements based both on precise facts about the domain as well
   as being able to use insights spread out across the
   literature. This combined strategy is likely to give a both broad
   and deep coverage of the domain.
*** Implementation
    For implementation an unstructured iterative process was used,
    this choice was made because the scope of the project was
    small. The development process continued continously until the
    developed artefact fullfilled the requirements identified.
*** Evaluation
    The evaluation of developed artefact was done using experimental
    methods. Experimental methods are often used for the verification
    of developed psychometric instruments. The goal with the
    instrument developed is generalization. By controlling irrelevant
    factors to the greatest extent possible researchers are better
    able to establish generalizability. This could, of course, reduce
    the ecological validity of the instrument. This reduction in
    ecological validity is a problem shared by many psychometric
    instruments.

** Requirements defintions
   For the literature review, a number of research publications
   related to emotional intelligence were reviewed. Based on these
   qualitative coding based analysis was performed. Different
   psychometric measures of emotional intelligence where coded based
   on theoretical models, scales and sub-scales. Similarly,
   stimulus-sets were coded based on the number of models, the number
   of models, emotions used, ethnicities represented etc. Based on
   these a number of criteria were identified.

   For the quantitative data analysis a data from a number of studies
   was used (see Table \ref{listofstudies}), which were analyzed separately. All the studies whose
   data was analyzed used the METT paradigm. 

   For the first study, overall hit-rates and descriptives were
   computed. A confusion matrix was then created created and a number
   of signal detection variables computed. These variables can be
   derived from $H$, the number of hits (true positives), $CR$, the
   correct rejections (true negatives), false alarms $FA$ (false
   positives), and misses $M$ (false negatives).

   \begin{equation} \label{e_hr}
   \mathit{HR} = \frac{H}{H + M}
   \end{equation}

   Equation \ref{e_hr} defines the Hit-rate, also called the
   True-postive rate or recall.

   \begin{equation} \label{e_crr}
   \mathit{CRR} = \frac{CR}{CR + FA}
   \end{equation}

   Equation \ref{e_crr} defines the Correct rejection rate, sometimes
   referred to as specificity.

   \begin{equation} \label{e_ppv}
   \mathit{PPV} = \frac{H}{H + FA}
   \end{equation}
   
   Equation \ref{e_ppv} defines the positive predictive value.

   \begin{equation} \label{e_npv}
   \mathit{NPV} = \frac{CR}{CR + M}
   \end{equation}
   
   Negative predictve value is defined according to Equation
   \ref{e_npv}.

   \begin{equation} \label{e_balanced_accuracy}
   \mathit{BalancedAccuracy} = \frac{HR + CRR}{2}
   \end{equation}

   Equation \ref{e_balanced_accuracy} defines the balanced accuracy.

   For the second study per-trial data, for the psychotherapist group
   was extracted. A cross tabulation of hits and misses for each trial
   was constructed such that the number of hits and misses by trial
   number could be investigated. This data was entered into a linear model.

   Finally, the results of the literature review and the quantitative
   analysis of earlier data were integrated to create requirements for
   for the artefact.

\input{summaryearlier.tex}

** Implementation
   An application was developed using the PsychoPy library
   \cite{Peirce2007}. The PsychoPy library was used because it offers
   excellent accuracy in the presentation of stimuli. Moreover,
   PsychoPy has excellent data-output components allowing ease of data
   collection. The software artefact designed for the present study
   was developed incrementally in iterations aiming to fullfill a
   growing subset of the requirements.
   
** Evaluation
   $N=?$ participants were administered the test
   software. Participants were positioned at a distance of 1m from the
   computer screen.

** Ethics
   Participation in the study was entirely voluntary, and participants
   signed informed concent forms prior to participating in the
   study. No identifying information was collected during the course
   of the study.


* Results
** Requirements Definition
*** Literature Review
    From reviewing the literature, a number of methods for measuring
    emotional intelligence were found, these are shown in table
    \ref{table:paradigms}. The paradigms discussed earlier cover many
    different aspects of emotional intelligence, and considers more
    instruments than can realistically be done in one study.

    \input{paradigms.tex}

    In addition to general test the different stimulus sets were
    considered. These stimulus sets are present in a tabular form in
    table \ref{table:stimsets}.

    \input{stimsets}


*** Analysis of old data
    The data-sets used in the study were analyzed separately with the
    goal of generating requirements for the system
    
    The first data-set contains 2149 correct responses and 1351
    incorrect responses for a total of hit-rate of 61%. A confusion
    matrix was computed as shown in table \ref{study1confusion}. In
    table \ref{study1classtable} characteristics for each emotion are
    shown.  
    
    \input{study-one-hitrates-emotion.tex}
    
    The second data-set consists of 72 subjects, the average accuracy
    was $72.99\%$ ($S=12.14$).
    
    #+CAPTION: Hit-rates and standard deviations by emotion in study 2.
    #+ATTR_LATEX: :environment tabulary :align lll :width \textwidth
    | Emotions  |  $HR$ |   $S$ |
    |-----------+-------+-------|
    | Disgust   |    64 | 25.98 |
    | Happiness | 90.05 | 18.98 |
    | Surprise  | 90.85 | 14.37 |
    | Anger     | 79.15 | 20.87 |
    | Contempt  | 57.25 | 33.88 |
    | Fear      | 68.75 | 23.75 |
    | Sadness   |  60.9 | 26.26 | 
    
    To investigate the effects of training, a linear model was
    constructed for the constructed with the number of trials as the
    independent variable and the hit-rate as the dependent
    variable. A significant effect of trial number was found
    ($t=4.56$, $p<0.001$, $df=68$).
     
*** Requirements

    In reviewing earlier research we found a number of suitable
    scales. Many of the standard measures of emotional intelligence
    are highly controversial. The least controversial measure is
    perhaps the METT, falling outside the traditional distinction of
    trait and state emotional intelligence. Another benefit is that
    the implementations of METT in our earlier data seems to possess
    many beneficial characteristics for such a test.

    However, it is unlikely that emotion recognition tasks can capture
    every aspect of emotional intelligence, some variance may be
    captured using other methods. On the other hand, using too many
    inventories may lead to a measure that takes too long to complete,
    reducing the reliability of the measure and increasing
    time-related costs. Therefore, it is important to keep any such
    tests as short as possible.

    MSCEIT, EQ-I, PEC contain a large number of items making them
    unsuitable, making them suitable for standalone use, but not using
    them in conjunction with other tests. This leaves TAS, RMITE and
    SPEC suitable as suitable candidates. RMITE, being a facial
    expression recognition task, is very similar to the METT and may
    for this reason be unsuitable to capture complementary sources of
    variance.

    TAS, while showing robustness, maturity and validity, is limited
    in that it only includes sub-factors related to
    alexithymia. Moreover, one of the factors, identifying feelings
    may overlap to some degree of overlap with METT. This makes it
    unsuitable as a supplementary scale to METT.

    Considering the aim of capturing qualitatively different factors
    from METT, SPEC may be the most appropriate scale. SPEC provides a
    the same number as factors as the longer PEC, while retaining much
    of the reliability. Given requirements of wide coverage of
    emotional intelligence factors as well as the time-constraints,
    SPEC seems to be the most suitable scale.

    Having considered the scales discussed in the literature review,
    the two scales need to be implemented, METT and SPEC. Specifically
    the test should implement a facial-expression tasks and a digital
    questionnaire, configured for METT and SPEC respectively.

    As discussed earlier \citep[recall][]{Calvo2008a} even a small
    difference in the duration of the display time of a METT trial, it
    is therefore important that display times are controlled to a
    resonable degree, to ensure this, among other, things display
    times need to be specified in numbers of frames so as to ensure
    precision.

    Because the experiment process is time-consuming, both for the
    participant and the experimenter, crashes in the software running
    experiments is waste valuable a lot of resources and can be
    frustrating for experimenters and participants alike.  It is
    therefore, important that the system is stable and avoids data
    loss to a as large extent possible given the resources.

    Using the keyboard is the most suitable input device for the test
    being developed, for several reasons. Firstly, it allows for
    faster responses once the user has learned the options. Second,
    not showing a mouse-cursor would avoid problems stemming from the
    occlusion of the stimulus by the mouse cursor. Finally, keyboards
    are commodity hardware and removes the need for purchasing
    specialized input hardware.

    Another issue is the effects of training, as the results showed,
    there was a strong effect of training. Specifically the earlier
    data showed a clear linear training trend. In the data-sets
    considered in the present study no end to this trend was
    found. The lack of an end suggests that training effects are still
    relevant after a substantial number of trials. For this reason, to
    ensure that data gathered using the scale is comparable between
    individuals, the number of trials need to be the same for all
    individuals.

    Finally, the issue of stimulus set should be addressed, in the
    data from earlier the earlier studies we found that performance
    was inline with what is typical for the paradigm, it therefore
    reasonable to assume that there are no additional issues with the
    RaFD data-set used in these. It seems appropriate then to use RaFD
    for evaluation studies while leaving data-set as a configurable
    variable.
    
    From these earlier conclusions a number of requirements were
    derived.

    1. METT test
       1. Functional: The system shall display a forward-mask
       2. Functional: The system shall display a backward-mask
       3. Functional: The system shall display a target-image
       4. Functional: The system shall display times shall be precise within  \SI{1/60}{\second}
       5. Functional: The system shall collect selected emotion input via the keyboard.
       6. Functional: The system shall perform the same number of trials for each participant.
       7. Functional: The system shall allow for the configuration of stimulus sets.
    2. SPEC-test
       1. Functional: The system shall show the questions
       2. Functional: The system shall collect numeric responses via keyboard input.
    3. Persistance
       1. Functional: The system shall persist results to disk in the CSV format.
       2. Non-functional: The system shall be stable to avoid data-loss
    4. Usability
       1. Non-functional: The system shall be simple to initialize




** Implementation
   #+INCLUDE: "result_implementation.org"

** Evaluation
   The test scores showed a correlation of X
   
* Discussion
  Discussion of the result of the entire study
** Conclusion
  What conclusions may be drawn?

\printbibliography


#  LocalWords:  parencite Mikolajczak citet Schlegel Ekman citep TK
#  LocalWords:  McCleskey Petrides Goleman MSCEIT PEC Brasseur EQ
#  LocalWords:  RaFD dataset fakeability
