# -*- compile-command: "./compile.sh" -*-
#+TITLE: Measuring EQ using micro-expressions
#+AUTHOR: William Rudenmalm
#+EMAIL: me@whn.se
#+BIBLIOGRAPHY: refs plain
#+OPTIONS: num:3 toc:2
#+LaTeX_HEADER: \input{preamble.tex}

* Introduction
  Emotions play a fundamental role in modulating the behavior and experiences
  of organisms, and while the exact definition is debated, its
  importance is not \parencite{Scherer2005}. The impact that emotions
  have on everyday life is enormous yet hard to pinpoint.
  
  \citet{Fontaine2007} defines emotions as a set of interrelated
  components, covering a wide range of behavior. These are appraisals
  of events, psychophysiological changes, motor expressions, action
  tendencies, subjective experience, and emotion regulation
  \parencite{Fontaine2007}. Emotions may have both internal
  and external antecedents \parencite{Scherer2005}.
  
  One important purpose of emotions is in regulating social
  interactions by facilitating group cohesion and collaboration. In
  social interactions, A key component is the ability to empathize with
  the emotions of others. \parencite{Niedenthal2012}.
  
  This ability referred to in the literature as emotional
  intelligence, has recently gained the attention of researchers. This
  ability to can be conceptualized as differences in the extent to
  which organisms interpret the emotions and affects of others. An
  essential component in emotional intelligence seems to be the
  ability to identify the emotions of oneself and
  others. \parencite{Mikolajczak2014}
  
  Other authors (Who?) have questioned the validity of emotional
  intelligence. Emotional intelligence has sometimes been found to be
  strongly correlated with personality factors. Calling into question
  the independence of emotional intelligence.
  
  Several approaches have been used to measure emotional
  intelligence. \citet{Mikolajczak2014} approached the measuring of
  emotional intelligence and developed a 50-item inventory for
  emotional intelligence. \citet{Baron-Cohen2001} approached the
  problem from a different angle asking participants to identify an
  emotion based just on a picture showing a pair of eyes. Another
  method is measuring emotional facial recognition
  \parencite{Schlegel2012}. Indeed, the results of \citet{Schlegel2012} seem
  to indicate that the recognition of emotional faces is a single ability
  as opposed to multiple separate abilities, lending validity to the
  construct of emotional intelligence.
  
  One approach that might be taken for emotional intelligence testing
  is using emotional facial expressions in a manner similar to
  \citet{Schlegel2012}. Indeed facial expressions, \citet{Ekman1969a}
  found, are to a large extent culturally invariant. The set of
  culturally invariant basic emotions \citet{Ekman1992} later defined
  as anger, fear, sadness, enjoyment, disgust and surprise.

  Cultural invariance is an important property for tests of emotional
  intelligence, suggesting that micro-expression recognition may be an
  appropriate measure of emotional competency. Indeed,
  \citet{Ekman2003} introduced the brief affect recognition task
  (BART) as a means by emotion recognition can be measured. One trial in
  the BART paradigm consists of a display of an emotional facial
  expression with forward- and backward masks of a neutral emotional
  face to avoid after-images \citep{Ekman2003}.

   
** Research problem
   Testing and training applications being a central part of
   micro-expression research \citep{Ekman1992}. However, despite
   multiple several studies being made \citep[e.g.][]{Schlegel2012},
   there exists no standard for testing emotion recognition using
   micro-expressions.

   The lack of a standard for testing emotion recognition may suggest
   a lack of understanding of what factors are important for
   developing tools for testing emotional intelligence. The present
   study sets out improve the understanding of how such testing
   software could be designed and aims to improve the accuracy and
   availability of such tests.

   The creation of such principles could be relevant for a number of
   areas. Firstly, education of psychologists, psychotherapists, and
   other mental health professionals might benefit from improved
   training tools. Second, applications in recruiting situations may
   help organizations make better recruitment decisions. Finally,
   psychological tests using the micro-expression paradigm may be
   improved using the principles.
     
** Research question
   What are the key principles for developing EQ-tests based on micro-expressions?
  
* Extended background


** The Theoretical Models of Emotional Intelligence
   The definition of emotional intelligence has been the subject of
   fierce debate \cite{McCleskey2014}. One of the key sources of
   controversy is whether emotional intelligence is to be considered an
   ability (Mayer, TK), a competency that can be learned \citep{Baron2006}
   or personality trait (Petrides TK). (TK Something about Goleman model)

   The notion of emotional intelligence as a competency is primarily
   advocated by \citep{Baron2006}. The Bar-On model is defined more
   precisely as a "cross-section of interrelated emotional and social
   competencies, skills and facilities that determine how effectively
   we understand and express ourselves, understand others and relate
   with them, and cope with daily demands" \citep{Baron2006}. The
   model is consistent with other frameworks in including both inter-
   and intra-personal skills. Like most other models of emotional
   intelligence, the Bar-On model considers widely different tasks,
   ranging from recognition to regulating emotions. (TK; REF)

   Writing only years after Baron's (TK, Doctoral dissertation)
   \cite{Salovey1990} introduced their notion of emotional
   intelligence, with the widely cited (TK, e.g) passage defining
   emotional intelligence as ``the subset of social intelligence that
   involves the ability to monitor one's own and others' feelings and
   emotions to discriminate among them and to use the information to
   guide one's thinking and actions''.  \citet{Salovey1990} also
   divided emotional intelligence into three sub-categories of
   emotional intelligence these are: appraisal and expression,
   regulation and utilization. \citet{Salovey1990} argue that people
   exhibiting these abilities might exhibit more adaptive
   behaviors. Conversely, people exhibiting deficits in emotional
   intelligence may sometimes show maladaptive behaviors.

   Some limited agreement can
   perhaps be captured as follows: emotional intelligence is a
   continuous factor determining behavior at the crossroads of emotion
   and cognition.
    
** Uses for emotional intelligence
   Emotional intelligence may also play a role in leadership. Indeed
   \citet{McCleskey} argues that for at least some aspects of
   leadership, it seems likely that emotional intelligence offers at
   least some predictive value for leadership roles \citet{McCleskey}.
   
   Moreover, emotional intelligence scales have been used for corporate
   recruiting for roles requiring social interaction. [REVISE]
   
   Measuring emotional intelligence has seen a number of different
   uses. One of the things where tests of emotional intelligence have
  been applied in testing for autism \parencite{Baron-Cohen2001}.

** Measuring emotional intelligence
    An early of for emotional intelligence is the Mayer-Salovey-Caruso
    Emotional Intelligence (MSCEIT), which in version 2.0 consisted of
    141 items across four facets of emotional intelligence
    \citep{Mayer2003}. MSCEIT rates participants on their performance
    on a set of eight tasks with two for each facet
    \citep{Mayer2003}. The MSCEIT tasks cover a number of emotional
    abilities including recognition of emotional pictures and faces,
    understanding and managing them \citep{Mayer2003}. One
    differentiating aspect of MSCEIT is its focus on emotional
    problem-solving. In an evaluation of MSCEIT 2.0 \citet{Mayer2003}
    found both sufficiently reliable as well as consistent with its
    theoretical foundations.

    Another interesting inventory for measuring emotional intelligence
    is the Profile of Emotional Competence (PEC), consisting of 50
    items divided into ten sub-scales \citep{Brasseur2013}. The PEC
    shows a good internal consistency, making it appropriate for both
    clinical and research use \citep{Brasseur2013}.

    Recently, \citet{Mikolajczak2014} were able to reduce the earlier
    PEC scale to only 20 items while maintaining the predictive
    properties of the original 50-item scale. This result suggests that
    emotional intelligence can be measured using only a small number
    of questions.

    Another method of measuring is Emotional Quotient-Inventory
    (EQ-I), a standard questionnaire consisting of 131-items divided
    over 15 sub-scales \citep{Bar-On1997}. The EQ-I is built on the
    theoretical framework based on emotional intelligence as a
    competency \citep{Baron2006}. However, the EQ-I is not without its
    problem. One large problem is that of fakeability, in one study
    conducted by \citet{GrubbIII2007}, found that participants when
    asked to "fake" emotional intelligence were able to do so. Such
    fakeability is quite troublesome because it would imply that it
    does not measure a competency, which would have been difficult to
    fake.


** Processing of emotional faces
   How faces are processed.
** Facial expressions
   The ability to process is an important social skill, 
*** Stimulus sets
    There exists a plethora of facial expression stimulus sets.

    One early stimulus set is the Japanese and Caucasian Facial
    Expressions of Emotion \citep[JACFEE;][]{matsumoto1988japanese}
    consisting of 56 photos of models of Japanese or Caucasian decent
    with eight pictures for each of the emotions. The dataset, while
    showing substantial cross-national differences also showed
    relatively high levels of agreement \citep{Biehl1997}.

    Another common data-set of emotional facial expression is the
    Karolinska Directed Emotional Faces
    \citep[KDEF;][]{DanielLundqvistAndersFlykt1998}. KDEF consists of
    pictures 70 of individuals expressing seven different emotions
    from five angles. KDEF has, since its inception, seen much use in
    facial expression research
    \citep[e.g.][]{Calvo2008a,Willis2006,Todorov2009}. In addition to
    widespread use, KDEF has shown good test-retest validity and a
    high degrees of accuracy in recognition tasks
    \citep{Goeleven2008}.

    A more recent contribution is the Raboud Faces Database
    \citep[RaFD;][]{Langner2010}. RaFD contains photographs of 49
    models expressing eight emotions with three gaze directions, taken
    from five camera angles for a total 5880 photographs
    \citep{Langner2010}. Upon validation, RaFD showed a very high
    accuracy, higher even than the earlier KDEF dataset
    \citep{Langner2010}. A key difference between RaFD and KDEF is the
    expression coaching given to models by a facial expression coding
    expert, which may explain the higher accuracy rates in RaFD
    \citep{Langner2010}.

    \citet{Calvo2008a} investigated the relationship between the
    display time (25-500ms) and the accuracy of emotion recognition
    for the KDEF stimulus set and found a slight increase in accuracy
    for longer displays. In addition, \citet{Calvo2008a} found
    differences in detection between the emotions. Happy and neutral
    showed higher degrees of accuracy than the other emotions and fear
    showed a lower accuracy.

    Taken together, the results of \citet{Calvo2008a} and SomeotherGuy
    suggest that there are differences in the accuracy of processing
    different emotions. Most importantly, it seems that accuracy rates
    for facial expressions of happiness and neutral expressions are
    much higher than those of other the expressions 
   \citep{Calvo2008a}. Care must, therefore,  be taken so as to avoid
    ceiling effects for happiness in particular.

    Another strand of research has gone into the split-second trait
    judgments made viewing a face. \cite{Willis2006} found very
    strong correlations between judgments of trustworthiness made
    after \SI{100}{\milli\second} or \SI{500}{\milli\second} versus
    those made without any time constraint. Moreover, no significant
    difference was found between the \SI{100}{\milli\second} and
    \SI{500}{\milli\second} conditions, suggesting that a trait
    judgment is performed very quickly. This notion was further
    expanded by \citet{Todorov2009}, finding that accuracy with
    display times up to \SI{100}{\milli\second}, after which the
    growth rate is dramatically slower.


* Methodology and Methods for Data Collection
** Research strategies
   Briefly describe different strategies 
** Chosen strategy
   Developing an artifact, therefore, design science.
** Different variants of design science
   Comparing Perjons & Johannesson v.s. earlier descriptions and our
   chosen approach.
** Stages in design science
   Description of the stages of design science
*** Chosen stages
    The following stages were chosen because they are the shortest
    way to reach an actual product.

    - Explicate requirements
    - Implementation
    - Evaluation
** Explicate requirements
   The requirements for the present study were created using two
   methods: 
  - A literature review for emotional intelligence
  - A quantitative analysis of existing data collected from a
    micro-expression test.
** Evaluation
    $N=?$ participants were administered the test software their results
    were compared to a questionnaire completed before the test.
*** Ethics
    Some ethical considerations.

* Results
** Requirements Definition
*** Literature
    Discuss papers in extended background Categorize results depending
    on what parts of the design they affect.
*** Analysis of old data
    Find the optimal level of difficulty to avoid 

** Implementation
   Using the requirements to create an artifact.

** Evaluation
   The test scores showed a correlation of X

* Discussion
  Discussion of the result of the entire study
** Conclusion
  What conclusions may be drawn.

\printbibliography


#  LocalWords:  parencite Mikolajczak citet Schlegel Ekman citep TK
#  LocalWords:  McCleskey Petrides Goleman MSCEIT PEC Brasseur EQ
#  LocalWords:  RaFD dataset fakeability
