# -*- compile-command: "./compile.sh" -*-
#+TITLE: Measuring EQ using Micro-expressions
#+AUTHOR: William Rudenmalm
#+EMAIL: me@whn.se
#+BIBLIOGRAPHY: refs plain
#+OPTIONS: num:3 toc:2
#+LaTeX_HEADER: \input{preamble.tex}

* Introduction
  Emotions play a key role in modulating the behaviour and experiences
  of organisms, and while the exact definition is debated, its
  importance is not \parencite{Scherer2005}. The impact that emotions
  have on everyday life are enormous yet hard to pinpoint.
  
  \citet{Fontaine2007} defines emotions as a set of interrelated
  components, covering a wide range of behaviour. These are appraisals
  of events, psychophysiological changes, motor expressions, action
  tendencies, subjective experience, and emotion regulation
  \parencite{Fontaine2007}. emotions may have both internal
  and external antecedents \parencite{Scherer2005}.
  
  One important function of emotions is in regulating social
  interactions by facilitating group cohesion and collaboration. A key
  factor in this is the ability to simulate or empathize with the
  emotions of others. \parencite{Niedenthal2012}.
  
  This ability referred to in the literature as Emotional
  intelligence, has recently gained the attention of researchers. This
  ability to can be conceptualized as differences in the extent which
  we process the emotions and affects of others. A key component in
  emotional intelligence seems to be the ability to identify the
  emotions of oneself and others. \parencite{Mikolajczak2014}
  
  Other authors (Who?) have questioned the validity of emotional
  intelligence. Emotional intelligence has in some cases been found to
  be strongly correlated with personality factors. Calling into
  question the independence of emotional intelligence.
  
  Several different approaches have been used to measure emotional
  intelligence. \citet{Mikolajczak2014} approached the measuring of
  emotional intelligence and developed a 50-item inventory for
  emotional intelligence. \citet{Baron-Cohen2001} approached the
  problem from a different angle asking participants to identify an
  emotion based just on a picture of a pair of eyes. Another approach
  is using the recognition of emotional facial expressions
  \parencite{Schlegel2012}. Moreover, the results of
  \citet{Schlegel2012} seem to indicate that the recognition of
  emotional faces is a single ability as opposed to multiple separate
  abilities, lending validity to the construct of emotional
  intelligence.
  
  One approach that might be taken for emotional intelligence testing
  is using emotional facial expressions in a manner similar to
  \citet{Schlegel2012}. Indeed facial expressions, \citet{Ekman1969a}
  found, are to a large extent culturally invariant. The set of
  culturally invariant basic emotions \citet{Ekman1992} later defined
  as: anger, fear, sadness, enjoyment, disgust and surprise.

  Cultural invariance is an important property for tests of emotional
  intelligence, suggesting that micro-expression recognition may be an
  appropriate measure of emotional competency. Indeed,
  \citet{Ekman2003} introduced the brief affect recognition task
  (BART) as means by emotion recognition can be measured. One trial in
  the BART paradigm consists of a display of an emotional facial
  expression with forward- and backward masks of a neutral emotional
  face to avoid after images \cite{Ekman2003}.

   
** Research problem
   Testing and training applications being a central part of
   micro-expression research \cite{Ekman1992}. However, despite
   multiple several studies being made \citep[e. g.][]{Schlegel2012},
   there exists no standard for testing emotion recognition using
   micro-expressions.

   This suggests that there may be a lack of understanding of what
   factors are important for developing tools for testing emotional
   intelligence. The present study sets out improve the understanding
   of how such testing software could be designed would greatly
   improve the accuracy and availability of such tests.

   This could be relevant for a number of areas. Firstly, education of
   psychologists, psychotherapists and other mental health
   professionals might benefit from improved training tools. Second,
   applications in recruiting situations. Finally, psychological tests
   using the micro-expression paradigm may be improved using the
   principles.
     
** Research question
   What are the key principles for developing EQ-tests based on Microexpressions.
  
* Extended background


** Emotional intelligence
*** Validity concerns
    Measuring emotional intelligence has seen a number of different
    uses. One of the things where tests of emotional intelligence have
    been applied in testing for autism.\parencite{Baron-Cohen2001}. 

    Moreover it the emotional intelligence scales have been used for
    corporate recruiting for roles requiring social interaction.
*** Trait vs Ability
*** Measurability
*** Construct validity
** Measuring emotional intelligence
*** PEC
    One intersting inventory for measuring emotional intelligence is
    the Profile of Emotional Competence (PEC), consisting of 50 items
    divided into ten subscales \citep{Brasseur2013}. The PEC shows a
    good internal consistency, making it appropriate for both clinical
    and research use \citep{Brasseur2013}.

    Recently, \citet{Mikolajczak2014} were able to reduce the earlier
    PEC scale to only 20 items while maintaining the predictive
    properties of the orignal 50-item scale. This suggests that
    emotional intelligence can be measured with only a small number of
    question.
*** EQ-I
    A standard questionarie model
*** MESQUITE
    Video-based system
** Processing of emotional stimuli
   How emotional stimuli are processed
** Processing of emotional faces
   How faces are processed.
** Micro-expressions
*** METT paradigm
*** Detection of microexpression vs display time
    \citet{Calvo2008a} investigated the relationship between the
    display time (25-500ms) and the accuracy of emotion recognition
    for the KDEF stimulus-set and found a slight increase in accuracy
    for longer displays. Moreover, \citet{Calvo2008a} found
    differences in detection between the emotions. Happy and neutral
    showed higher degrees of accuracy than the other emotions and fear
    showed a lower accuracy.

    Taken togeter, the results of \citet{Calvo2008a} and SomeotherGuy
    suggest that there are differences in the accuracy of processing
    different emotions. Most importantly, it seems that accuracy rates
    for facial expressions of happiness and neutral expressions are
    much higher than those of other the expressions
    \citep{Calvo2008a}. Care must therefore be taken so as to avoid
    ceiling effects for happiness in particular.


* Methodology and Methods for Data collection
** Research strategies
   Briefly describe different strategies 
** Chosen type of strategy
   Developing an artefact, therefore design science.
** Different variants of design science
   Comparing Perjons & Johannesson vs earlier descriptions and our
   chosen approach.
** Stages in design science
   Description of the stages in design science
*** Chosen stages
    The following stages where chosen because they are the shortest
    way to reach an actual product.

    - Explicate requirements
    - Implementation
    - Evaluation
** Explicate requirements
   The requirements for the present study were created using two
   methods: 
  - A litterature review for emotional intelligence
  - A quantitative analysis of existing data collected from a
    microexpression test.
** Evaluation
    $N=?$ participants were administered the test-software their results
    were compared to a questionarie completed before the test.
*** Ethics
    Some ethical considerations.

* Results
** Requirments Definition
*** Litterature
    Discuss papers in extended background Categorize results depending
    on what parts of the design they affect.
*** Analysis of old data
    Find the optimal level of difficulty to avoid 

** Implementation
   Using the requirements to create an artefact.

** Evaluation
   The test-scores showed a correlation of X

* Discussion
  Discussion of the result of the entire study
** Conclusion
  What conclusions may be drawn.

\printbibliography

