# -*- compile-command: "./compile.sh" -*-
#+TITLE: A novel, multi-model, multi-task, method for computerized testing of emotional intelligence
#+AUTHOR: William Rudenmalm
#+EMAIL: me@whn.se
#+BIBLIOGRAPHY: refs plain
#+OPTIONS: num:3 toc:2
#+LaTeX_HEADER: \input{preamble.tex}

* Introduction
  Emotions play a fundamental role in modulating the behavior and experiences
  of organisms, and while the exact definition is debated, its
  importance is not \parencite{Scherer2005}. The impact that emotions
  have on everyday life is enormous yet hard to pinpoint.
  
  \citet{Fontaine2007} defines emotions as a set of interrelated
  components, covering a wide range of behavior. These are appraisals
  of events, psychophysiological changes, motor expressions, action
  tendencies, subjective experience, and emotion regulation
  \parencite{Fontaine2007}. Emotions may have both internal
  and external antecedents \parencite{Scherer2005}.
  
  One important purpose of emotions is regulating social interactions
  by facilitating group cohesion and collaboration. Understanding the
  emotions of other the emotions of others is a key aspect of many
  social situations. \parencite{Niedenthal2012}.
  
  The ability to process the emotional information contained both in
  oneself and others, is referred to in the literature as emotional
  intelligence. Emotional intelligence has over the last
  two-and-a-half decades gained the attention of researchers. This
  ability to can be conceptualized as differences in the extent to
  which organisms interpret, process and act upon the emotions and
  affects of themselves and others. An essential component in
  emotional intelligence seems to be the ability to identify the
  emotions of oneself and others. \parencite{Mikolajczak2014} 
  
  The concept of emotional intelligence is not uncontroversial, with
  different authors suggesting widely different models of emotional
  intelligence \citep{McCleskey2014,Mayer2008,Petrides2010}. Other
  authors (TK, Who? Locke surely) have questioned the validity of
  emotional intelligence. Indeed, emotional intelligence has been
  found to correlate with personality factors
  \citep[e.g.][]{Warwick2004, Petrides2001} and cognitive abilities
  \citep[e.g.][]{Freudenthaler2007}, calling into question the
  divergent validity, to that point of some authors (TK Locke and
  someone else) doubting the concepts usefulness.
  
  Several approaches have been used to measure emotional intelligence,
  both ability tests \citep{Mayer2003}, self-reported ability
  \citep{Bar-On1997}, and trait measures (TK, ref),
  \citet{Mikolajczak2014} approached the measuring of emotional
  intelligence and developed a 50-item inventory for emotional
  intelligence. More specialized \citet{Baron-Cohen2001} approached
  the problem from a different angle asking participants to identify
  an emotion based just on a picture showing a pair of eyes. Another
  strand of research is focused on measuring emotional facial
  recognition \parencite{Schlegel2012}. The results of
  \citet{Schlegel2012} seem to indicate that the recognition of
  emotional faces is a single ability as opposed to multiple separate
  abilities, affirming to some degree the convergent validity to the
  construct of emotional intelligence.
  
  One approach that might be taken for emotional intelligence testing
  is using emotional facial expressions in a manner similar to
  \citet{Schlegel2012}. Indeed facial expressions, \citet{Ekman1969a}
  found, are to a large extent culturally invariant. The set of
  culturally invariant basic emotions \citet{Ekman1992} later defined
  as anger, fear, sadness, enjoyment, disgust and surprise.

  Cultural invariance is an important property for tests of emotional
  intelligence, suggesting that micro-expression recognition may be an
  appropriate measure of emotional competency. Indeed,
  \citet{Ekman2003} introduced the brief affect recognition task
  (BART) as a means by emotion recognition can be measured. One trial in
  the BART paradigm consists of a display of an emotional facial
  expression with forward- and backward masks of a neutral emotional
  face to avoid after-images \citep{Ekman2003}.

   
** Research problem
   Testing and training applications being a central part of
   micro-expression research \citep{Ekman1992}. However, despite
   multiple several studies being made \citep[e.g.][]{Schlegel2012},
   there exists no standard for testing emotion recognition using
   micro-expressions.

   The lack of a standard for testing emotion recognition may suggest
   a lack of understanding of what factors are important for
   developing tools for testing emotional intelligence. The present
   study sets out improve the understanding of how such testing
   software could be designed and aims to improve the accuracy and
   availability of such tests.

   The creation of such principles could be relevant for a number of
   areas. Firstly, education of psychologists, psychotherapists, and
   other mental health professionals might benefit from improved
   training tools. Second, applications in recruiting situations may
   help organizations make better recruitment decisions. Finally,
   psychological tests using the micro-expression paradigm may be
   improved using the principles.
     
** Research question
   What are the key principles for developing EQ-tests based on micro-expressions?
  
* Extended background


** The Theoretical Models of Emotional Intelligence
   The definition of emotional intelligence has been the subject of
   fierce debate \cite{McCleskey2014}. One of the key sources of
   controversy is whether emotional intelligence is to be considered an
   ability \citep{Salovey1990}, a competency that can be learned \citep{Baron2006}
   or personality trait \citep{Petrides2007}. (TK Something about Goleman model)

   The notion of emotional intelligence as a competency is primarily
   advocated by \citep{Baron2006}. The Bar-On's model is defined more
   precisely as a "cross-section of interrelated emotional and social
   competencies, skills and facilities that determine how effectively
   we understand and express ourselves, understand others and relate
   with them, and cope with daily demands" \citep{Baron2006}. The
   model is consistent with other frameworks in including both inter-
   and intra-personal skills. Like most other models of emotional
   intelligence, the Bar-On model considers widely different tasks,
   ranging from recognition to regulating emotions. (TK; REF)

   Writing only years after Bar-On (TK, Doctoral dissertation)
   \cite{Salovey1990} introduced their notion of emotional
   intelligence, with the widely cited (TK, e.g) passage defining
   emotional intelligence as ``the subset of social intelligence that
   involves the ability to monitor one's own and others' feelings and
   emotions to discriminate among them and to use the information to
   guide one's thinking and actions''.  \citet{Salovey1990} also
   divided emotional intelligence into four sub-categories of
   emotional intelligence these are: appraisal, expression,
   regulation and utilization. \citet{Salovey1990} argue that people
   exhibiting these abilities might exhibit more adaptive
   behaviors \citep{Brackett2006}. Conversely, people exhibiting deficits in emotional
   intelligence may show maladaptive behaviors \citep{Brackett2006}.

   Beginning with \citet{Petrides2001}, one strand of research has
   separated emotional intelligence into trait and ability components
   \citep[e.g.][]{Petrides2007, Petrides2010}. Indeed, a growing body
   of evidence seems to indicate that some parts of emotional
   intelligence is explained by personality factors
   \citep[e.g.][]{Warwick2004, Petrides2001}. Specifically,
   \citet{Warwick2004} found correlations between personality factors
   and trait emotional intelligence. Building on these results
   \citet{Petrides2007}, argues that while trait emotional
   intelligence is a personality trait and uncorrelated to ability
   measures of emotional intelligence, it is distinct from traditional
   personality factors. The incompatibility argument is expanded
   further by \citet{Petrides2010}, arguing that trait and ability
   measures of emotional intelligence cannot be grouped in any
   meaningful sense. Moreover, \citet{Petrides2010} criticizes the
   Bar-On \citep{Baron2006} model as well as the \citet{Salovey1990}
   model, arguing that ability measures of emotional intelligence
   imply the existence of some universal notion of adaptive social
   behavior.

   To resolve some of the controversy regarding the definition of the
   term \citet{Cherniss2010} suggests separating the concepts of
   emotional intelligence and social competence, defining emotional
   intelligence simply as the recognizing, reasoning and regulating
   emotions, holding that factors are simply emotional and social
   competencies. In effect \citet{Cherniss2010}, designates the
   \citet{Salovey1990} model as emotional intelligence, while
   referring to the Bar-On model \citep{Baron2006} as emotional and
   social competence. This attempt to reconcile different theories of
   emotional intelligence was criticized by \cite{Petrides2010} for
   severing the link between the constructs and their present 
   operational definitions.

   The separation of trait and state concepts of emotional
   intelligence is supported by most authors
   \citep[e.g.][]{Petrides2010,McCleskey2014,DiFabio2014} (TK,
   Askhanasy). What this separation entails, however, is a matter of
   debate. Proponents of the trait model of emotional intelligence
   such as, \citet{Petrides2010} argue that ability measures of
   emotional intelligence are lacking. While proponents of the ability
   model argue that trait models is simply personality. Another
   approach was taken by \citet{Freudenthaler2007}, interpreting trait
   and ability as typical and maximum performance respectively,
   finding typical performance as dependent on personality and maximum
   performance as dependent on cognitive ability.

   Some limited agreement can perhaps be captured as follows:
   emotional intelligence is a continuous factor determining the depth
   and accuracy of processing at the crossroads of emotion and
   cognition.
    
** Uses for emotional intelligence

   In a review by \citet{Mayer2008} identified seven key results of
   emotional intelligence research, these were:
#+BEGIN_QUOTE
   1. Better social relations for children.
   2. Better social relations for adults. Among
   3. High-EI individuals are perceived more positively by others.
   4. Better family and intimate relationships.
   5. Better academic achievement. [not accounting for IQ]
   6. Better social relations during work performance and in negotiations.
   7. Better psychological well-being.
#+END_QUOTE

   It seems that within the aforementioned areas emotional
   intelligence, at least to some degree predicts outcomes.

   It is commonly held that emotional intelligence plays a role in
   leadership
   \citep{Brackett2006,McCleskey2014}. \citet{McCleskey2014} argues
   that for at least some aspects of leadership, it seems likely that
   emotional intelligence offers at least some predictive value for
   leadership roles \citep{McCleskey2014}.
   
   Moreover, emotional intelligence scales have been used for
   corporate recruiting for roles requiring social interaction (TK,
   REF). One of the things where tests of emotional intelligence have
   been applied in testing for autism \parencite{Baron-Cohen2001}. In
   this particular case, a specific test of emotion recognition,
   reading the mind in the eyes, was developed \citep{Baron-Cohen2001}.

** Measuring emotional intelligence of Ability
    An early measure of emotional intelligence is the
    Mayer-Salovey-Caruso Emotional Intelligence (MSCEIT), which is
    based on the theoretical framework introduced by
    \citep{Salovey1990}. In version 2.0 it consisted of 141 items
    across four facets of emotional intelligence
    \citep{Mayer2003}. MSCEIT attempts measure performance based on a
    set of eight tasks with two for each facet \citep{Mayer2003}. The
    MSCEIT tasks cover a number of emotional abilities including
    recognition of emotional pictures and faces, understanding and
    managing them \citep{Mayer2003}. One differentiating aspect of
    MSCEIT is its focus on emotional problem-solving. In an evaluation
    of MSCEIT 2.0 \citet{Mayer2003} found both sufficiently reliable
    as well as consistent with its theoretical foundations. The
    validity however been disputed, \citet{Rossen2008} found results
    running contrary to the factor structure used found by
    \citet{Mayer2003}. The results found by \citet{Rossen2008} seem to
    suggest that the sub-scales do not match the intended theoretical
    concepts. For measuring trait emotional intelligence
    \cite{Salovey1995} introduced Trait meta-mood scale (TTMS) which
    aims to measure the tendency to attend to ones moods and emotions,
    this scale has been found not to correlate with MSCEIT
    \citep{Warwick2004}.

    Another interesting inventory for measuring emotional intelligence
    is the Profile of Emotional Competence (PEC), consisting of 50
    items divided into ten sub-scales \citep{Brasseur2013}. The PEC
    shows a good internal consistency, making it appropriate for both
    clinical and research use \citep{Brasseur2013}.

    Recently, \citet{Mikolajczak2014} were able to reduce the earlier
    PEC scale to only 20 items while maintaining the predictive
    properties of the original 50-item scale. This result suggests that
    emotional intelligence can be measured using only a small number
    of questions.

    Another method of measuring is Emotional Quotient-Inventory
    (EQ-I), a standard questionnaire consisting of 131-items divided
    over 15 sub-scales \citep{Bar-On1997}. The EQ-I is built on the
    theoretical framework based on emotional intelligence as a
    competency \citep{Baron2006}. However, the EQ-I is not without its
    problems. One large problem is that of fakeability, in one study
    conducted by \citet{GrubbIII2007}, found that participants when
    asked to "fake" emotional intelligence were able to do so. Such
    fakeability is quite troublesome because it would imply that it
    does not measure a competency, which would have been difficult to
    fake.


** Processing of emotional faces
   How faces are processed.
** Facial expressions
   The ability to process is an important social skill, 
*** Stimulus sets
    There exists a plethora of facial expression stimulus sets.

    One early stimulus set is the Japanese and Caucasian Facial
    Expressions of Emotion \citep[JACFEE;][]{matsumoto1988japanese}
    consisting of 56 photos of models of Japanese or Caucasian decent
    with eight pictures for each of the emotions. The dataset, while
    showing substantial cross-national differences also showed
    relatively high levels of agreement \citep{Biehl1997}.

    Another common data-set of emotional facial expression is the
    Karolinska Directed Emotional Faces
    \citep[KDEF;][]{DanielLundqvistAndersFlykt1998}. KDEF consists of
    pictures 70 of individuals expressing seven different emotions
    from five angles. KDEF has, since its inception, seen much use in
    facial expression research
    \citep[e.g.][]{Calvo2008a,Willis2006,Todorov2009}. In addition to
    widespread use, KDEF has shown good test-retest validity and a
    high degrees of accuracy in recognition tasks
    \citep{Goeleven2008}.

    A more recent contribution is the Raboud Faces Database
    \citep[RaFD;][]{Langner2010}. RaFD contains photographs of 49
    models expressing eight emotions with three gaze directions, taken
    from five camera angles for a total 5880 photographs
    \citep{Langner2010}. Upon validation, RaFD showed a very high
    accuracy, higher even than the earlier KDEF dataset
    \citep{Langner2010}. A key difference between RaFD and KDEF is the
    expression coaching given to models by a facial expression coding
    expert, which may explain the higher accuracy rates in RaFD
    \citep{Langner2010}.

    \citet{Calvo2008a} investigated the relationship between the
    display time (25-500ms) and the accuracy of emotion recognition
    for the KDEF stimulus set and found a slight increase in accuracy
    for longer displays. In addition, \citet{Calvo2008a} found
    differences in detection between the emotions. Happy and neutral
    showed higher degrees of accuracy than the other emotions and fear
    showed a lower accuracy.

    Taken together, the results of \citet{Calvo2008a} and SomeotherGuy
    suggest that there are differences in the accuracy of processing
    different emotions. Most importantly, it seems that accuracy rates
    for facial expressions of happiness and neutral expressions are
    much higher than those of other the expressions 
   \citep{Calvo2008a}. Care must, therefore,  be taken so as to avoid
    ceiling effects for happiness in particular.

    Another strand of research has gone into the split-second trait
    judgments made viewing a face. \cite{Willis2006} found very
    strong correlations between judgments of trustworthiness made
    after \SI{100}{\milli\second} or \SI{500}{\milli\second} versus
    those made without any time constraint. Moreover, no significant
    difference was found between the \SI{100}{\milli\second} and
    \SI{500}{\milli\second} conditions, suggesting that a trait
    judgment is performed very quickly. This notion was further
    expanded by \citet{Todorov2009}, finding that accuracy with
    display times up to \SI{100}{\milli\second}, after which the
    growth rate is dramatically slower.


* Methodology and Methods for Data Collection
** Research strategies
   Briefly describe different strategies 
** Chosen strategy
   Developing an artifact, therefore, design science.
** Different variants of design science
   Comparing Perjons & Johannesson v.s. earlier descriptions and our
   chosen approach.
** Stages in design science
   Description of the stages of design science
*** Chosen stages
    The following stages were chosen because they are the shortest
    way to reach an actual product.

    - Explicate requirements
    - Implementation
    - Evaluation
** Explicate requirements
   The requirements for the present study were created using two
   methods: 
  - A literature review for emotional intelligence
  - A quantitative analysis of existing data collected from a
    micro-expression test.
** Evaluation
    $N=?$ participants were administered the test software their results
    were compared to a questionnaire completed before the test.
*** Ethics
    Some ethical considerations.

* Results
** Requirements Definition
*** Literature
    Discuss papers in extended background Categorize results depending
    on what parts of the design they affect.
*** Analysis of old data
    Find the optimal level of difficulty to avoid 

** Implementation
   Using the requirements to create an artifact.

** Evaluation
   The test scores showed a correlation of X

* Discussion
  Discussion of the result of the entire study
** Conclusion
  What conclusions may be drawn.

\printbibliography


#  LocalWords:  parencite Mikolajczak citet Schlegel Ekman citep TK
#  LocalWords:  McCleskey Petrides Goleman MSCEIT PEC Brasseur EQ
#  LocalWords:  RaFD dataset fakeability
