The resulting artifacts in comprised of a number of parts. These
are, the METT module, the questionnaire module, run-time
configuration, deployment scripts and text assets. These components
are replaceable with other components on an as-needed basis.

* Configuration
  The Pyton modules expects configuration in the JavaScript Object
  Notation (JSON). These configuration artifacts consists of three
  separate files. One with overall configuration global applicable to
  each trial and question of the experiment. The second file
  specifies paths to image files for masks and stimuli as well as
  correct responses for each individual trial of the METT
  paradigm. Finally, a third JSON file specifies the questions for
  SPEC.

* Deployment scripts
  To simplify the configuration and use of the system a number of
  utility scripts were developed, including scripts for generating
  subsets of the RaFD, starting the system in a given configuration
  state, and running a demonstration mode of the software. These
  scripts are not run in the normal operations of the script, however,
  they are useful in setting up an environment that can then be
  reused.

* Text assets
  For the purposes of making the application locablizable to different
  languages, a system for text assets was created. Text assets for two
  languages, Swedish and English were created. These assets are used
  to progrmatically translate the application.

* METT module
  Before the experiment is started, the module shuffles the order of
  trials used in the experiment. This results in each participant
  getting a psuedo-random and non-systematic order of trials. 

  The trials are then invoked in order. Upon invocation the trial
  handler loads the relevant from disk, showing a blank screen
  meanwhile. Once the images have been loaded the picture of the
  neutral expression is showed a fixed, configurable number of
  frames. Once the configured number of frames has been rendered, the
  emotional picture also for a configurable but different number of
  frames. Then, finally the neutral image is shown for the configured
  number of frames. After this, the system displays an input prompt
  and starts accepting keyboard input from the users. Once an answer
  has been collected , the screen is then cleared and the trial yields
  control back to the ex periment.

  Once the set of trials has been completed, the system, takes the
  trial data and combines it with the response data. This results in a
  one-row per trial data-set, which is then serialize and saved to
  disk as a csv-file.

* Questionarie module
  After the METT module has completed its work the questionarie module
  is initialized. Each question present in configuration is then
  presented in order. The presentation of a question is performed as
  follows, first, the question text and the response options are
  rendered to the screen as text. Keyboard input is read. If the input
  read matches a response alternative, the data is then stored in
  memory. This process is repeated each question of the configuration
  has been processed. After the questinarie task is completed the
  results are saved to disk in the csv format.


