The resulting artifacts in comprised of a number of parts. These are,
the METT module, the questionnaire module, run-time configuration,
deployment scripts and text assets. These components are replaceable
with other components on an as-needed basis. A graphical
representation of the module dependencies is presented in figure
\ref{fig:modules}.

#+BEGIN_LATEX
  \begin{figure}[htpb]
    \centering
    \label{fig:modules}
    \begin{tikzpicture}[
        scale=2.0,
        align=center,node distance=5cm
        every node/.style={draw,circle,very thick}
      ]

      \graph [] {
        Experiment -> {
          METT,
          Questionnarie,
          Config,
          Questionnarie -> UI,
          Config -> Util,
          UI -> Util,
        }
      };
    \end{tikzpicture}
    \caption{Graph of dependencies in the software artefact}
  \end{figure}
#+END_LATEX

* Software support for artefact configuration
  The Pyton modules expects configuration in the JavaScript Object
  Notation (JSON). These configuration artifacts consists of three
  separate files.

  One with overall configuration global applicable to each trial and
  question of the experiment. This file is stored with the filename
  \texttt{options.json}, and an example of its syntax in listing
  \ref{lst:options}.

  \begin{lstlisting}[caption={\texttt{options.json} Configuration file},label={lst:options}]
  {
    "NameOfTheExperiment": {
      "forward_mask_frames": 40
      "backward_mask_frames": 40,
      "expression_frames": 12,
      "intertrial_interval": 2,
   }
  }
  \end{lstlisting}

  The second file, \texttt{trials.json} specifies paths to image files
  for masks and stimuli as well as correct responses for each
  individual trial of the METT paradigm. An example of the syntax used
  for this file is presented in listing \label{lst:trials}.

  \begin{lstlisting}[caption={\texttt{trials.json} trials file},label={lst:trials}]
  {
    "NameOfTheExperiment": [
      {"stim": "PathToStimulus.JPG", "neu": "PathToMask.png", "correct": 5},
      // ...
    ]
  }
  \end{lstlisting}

  Finally, a third JSON, \texttt{questions.json} file specifies the
  questions for SPEC, and the keymaps coding keypreses to responses,
  an example of this file is shown in listing \ref{lst:questions}.

  \begin{lstlisting}[caption={\texttt{questions.json} questions specification file},label={lst:questions}]
  {
    "NameOfTheExperiment": [
       {
         "question_id": 25,
         "responses": {
           "1": "Option One",
           // ...
         },
         "text": "Question"
       }
     // ..
    ]
  }
  \end{lstlisting}
 
* Tools for artefact deployment
  To simplify the configuration and use of the system a number of
  utility scripts were developed, including scripts for generating
  subsets of the RaFD, starting the system in a given configuration
  state, and running a demonstration mode of the software. These
  scripts are not run in the normal operations of the appliation,
  however, they are useful in setting up an environment that can then
  be reused.

* Text assets and translation
  For the purposes of making the application locablizable to different
  languages, a system for text assets was created. Text assets such as
  instructions can be created on a as needed basis. These assets are
  used to progrmatically translate the application.
 
* Initialization module
  The initialization module of the system manages initializing the
  system on load. The first task of the is to collect the subject
  identifier and experimenter initials from the experimenter. Once
  this is performed, the current time and hostname are also collected
  to help with diagnostics. The module then delegates to the
  configuration modules which then proceeds to deserialize
  configuration files and load the configuration files into
  memory. After loading files passes-on the trials to the METT module
  which displays performs the trials. When the METT module has
  performed as its trials, the initialization module invokes the
  question module, passing on the questions. When both METT and
  questions have completed, collected responses are written to CSV.

* METT module
  Before the experiment is started, the module shuffles the order of
  trials used in the experiment. This results in each participant
  experiencing the trials in a psuedo-random, non-systematic order
  of trials.

  The trials are then invoked in order, upon invocation the trial
  handler loads the relevant images from disk, showing a blank screen
  while loading. Once the images have been loaded the picture of the
  neutral expression is showed for a fixed, but configurable number of
  frames. Once the configured number of frames have rendered, the
  emotional picture is displayed, for a configurable but different
  number of frames. Then, finally the neutral image is shown for the
  another configured number of frames.

  Once the pictures have been displayed, the system displays an input
  prompt and starts accepting keyboard input from the user. Once an
  answer has been collected , the screen is then cleared. The flow of
  execution then halts for a configurable number of seconds before the
  trial yields control back to experiment.

  Once the set of trials has been completed, the system, takes the
  trial data and combines it with the response data. This results in a
  one-row per trial data-set, which is then serialize and saved to
  disk as a comma separated values file.

* Questionarie module
  After the METT module has completed its work the questionarie module
  is initialized, each question consists of three components, a
  \texttt{question-id} which is simply logged to the output, a text description
  for prompting the user, and finally a mapping, \texttt{keymap}, between keyboard key
  names and a text-string containing the question text.

  Each question present in configuration is then presented in
  order. The presentation of a question is performed as follows,
  first, the question text and the response options are rendered to
  the screen as text. Keyboard input is read. If the input read
  matches a response alternative, the key and response time are then
  stored in memory. This process is repeated untill each configured
  question has been performed.  has been processed. After the
  questinarie task is completed the results are saved to disk in the
  comma separated value format.

* Output
  Both the questionnarie and METT modules write their results to disk
  in the CSV format with filenames generated using the current time
  and hostname of the host running the application. The output was
  designed in order to be as simple as possible, useble in many
  different statistical computational environments. An example of the
  output of the METT and questionnarie modules can be found in
  listings \ref{lst:resultmett} and \ref{lst:resultquestionnarie}
  respectively.

  #+BEGIN_LATEX
  \begin{lstlisting}[caption={Excerpt of a METT output file: first three lines},label={lst:resultmett}]
  stim,response,emotion,correct,rt
  img/Rafd090_03_Caucasian_male_fearful_frontal.jpg,3,4,0,0.12610292434692383
  img/Rafd090_03_Caucasian_male_contemptuous_frontal.jpg,3,2,0,0.0313420295715332
  \end{lstlisting}
  #+END_LATEX

  #+BEGIN_LATEX
  \begin{lstlisting}[caption={Excerpt of a questionnarie output file: first three lines},label={lst:resultquestionnarie}]
  question_id,value,rt
  0,3,1.4653780460357666
  1,3,0.08734989166259766
  \end{lstlisting}
  #+END_LATEX

